version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: flowbit-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - flowbit-network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: flowbit-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/flowbit?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key
      - N8N_WEBHOOK_SECRET=n8n-webhook-secret-key
      - N8N_BASE_URL=http://n8n:5678
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - flowbit-network

  shell:
    build:
      context: ./shell
      dockerfile: Dockerfile
    container_name: flowbit-shell
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - api
    volumes:
      - ./shell:/app
      - /app/node_modules
    networks:
      - flowbit-network

  support-tickets-app:
    build:
      context: ./support-tickets-app
      dockerfile: Dockerfile
    container_name: flowbit-support-tickets
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - PORT=3002
    depends_on:
      - api
    volumes:
      - ./support-tickets-app:/app
      - /app/node_modules
    networks:
      - flowbit-network

  n8n:
    image: n8nio/n8n:latest
    container_name: flowbit-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DISABLE_UI=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    networks:
      - flowbit-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: flowbit-ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    command: ["http", "api:3001"]
    depends_on:
      - api
    networks:
      - flowbit-network

volumes:
  mongo_data:
  n8n_data:

networks:
  flowbit-network:
    driver: bridge
